knorth55/jsk_robot

- jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/amcl_node.xml
`~omni_model_type` parameter in amcl, which was set to `omni`, has a bug and it is recommended to use `omni-corrected`.
See also: http://wiki.ros.org/amcl
> [WIP] Update amcl parameters

- jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.xml
- jsk_fetch_robot/jsk_fetch_startup/euslisp/go-to-kitchen.l
add rosbag record for go_to_kitchen demo
Now i'm testing on Fetch15
cc. @708yamaguchi @pazeshun @sktometometo
> add rosbag record for go_to_kitchen demo

- jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.xml
- jsk_fetch_robot/jsk_fetch_startup/launch/rosbag_play.launch
- jsk_fetch_robot/jsk_fetch_startup/launch/rosbag_record.launch
- jsk_fetch_robot/jsk_fetch_startup/scripts/latched_topic_republisher.py
- add rosbag_record.launch and rosbag_play.launch to jsk_fetch_startup
- these launch files enables to record and play rosbag files including latched topic like statc_tf
- add latched_topic_republihser.py
- this script enables to republishe latched topic like tf_static from a rosbag file.
- changed rosbag procedure in daily kitchen demo to rosbag_record.launch
> [fetch] update rosbag record and play

- jsk_fetch_robot/jsk_fetch_startup/config/jsk_startup.rviz
- jsk_fetch_robot/jsk_fetch_startup/launch/rosbag_play.launch
- jsk_fetch_robot/jsk_fetch_startup/launch/rosbag_record.launch
- jsk_fetch_robot/jsk_fetch_startup/scripts/latched_topic_republisher.py
Refactor version of #12 
- update `rosbag_play.launch`
- fix `latched_topic_publisher.py`
cc. @sktometometo
> Fetch rosbag record and play

- jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml
- jsk_robot_common/jsk_robot_startup/README.md
- jsk_robot_common/jsk_robot_startup/launch/safe_teleop.launch
I brought https://github.com/jsk-ros-pkg/jsk_robot/pull/1234/commits/2ec58ad8d5daaf15e114fd6291713ecffd97ef65
I tested with real fetch15 robot.
> Do not use multiple safe_teleop_base to reduce CPU load for fetch

- jsk_fetch_robot/jsk_fetch_startup/launch/fetch_teleop.xml
- jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base/safe_teleop.xml
- jsk_robot_common/jsk_robot_startup/README.md
- jsk_robot_common/jsk_robot_startup/launch/safe_teleop.launch
- jsk_robot_common/jsk_robot_startup/util/mux_selector.py
this is PR2 branch PR of https://github.com/jsk-ros-pkg/jsk_robot/pull/1234
cc. @708yamaguchi
> [WIP] update jsk_pr2_move_base to new jsk common teleop base system

- jsk_fetch_robot/jsk_fetch_startup/launch/rosbag_record.launch
This PR is for fetch to get audio data from rosbag.
> add audio to rosbag record

- jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
To update global costmap automatically on rviz, I updated global_costmap/update_frequency.
http://wiki.ros.org/costmap_2d#costmap_2d.2Flayered.Rate_parameters
> add publish_frequency to global_costmap

- jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
To make fetchs' CPU load low, I added args for what nodes to launch.
> add args for what nodes to launch on fetch_bringup.launch

- jsk_fetch_robot/jsk_fetch.rosinstall.melodic
- jsk_fetch_robot/jsk_fetch_startup/README.md
- jsk_fetch_robot/jsk_fetch_startup/launch/fetch.launch
- jsk_fetch_robot/jsk_fetch_startup/launch/fetch_t265.launch
- jsk_fetch_robot/jsk_fetch_startup/scripts/odometry_transformer.py
> fix t265 odometry launch

- jsk_fetch_robot/jsk_fetch_startup/launch/fetch.launch
- jsk_fetch_robot/jsk_fetch_startup/upstart_scripts/robot.conf
- add `use_realsense` arg to fetch.launch
- disable `use_realsense` and `use_base_camera_mount` of fetch.launch in robot.conf
> bugfix for indigo

- jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l
> [jsk_fetch_startup] fix parenthesis

- jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l
Update go-to-kitchen demo
- Fix goal offset
- Fix returning rotation angle
> [jsk_fetch_startup] fix coordinate values of go-to-kitchen

- jsk_fetch_robot/jsk_fetch_startup/launch/navigation/fetch_move_base_common_params.yaml
- jsk_fetch_robot/jsk_fetch_startup/package.xml
This PR is based on https://github.com/knorth55/jsk_robot/pull/77.
change base_local_planner to teb_local_planner.
> [jsk_fetch_startup] change base local planner to teb local planner

- jsk_fetch_robot/jsk_fetch_startup/launch/navigation/fetch_move_base_common_params.yaml
add [speak_and_wait_recovery](https://github.com/jsk-ros-pkg/jsk_common/pull/1681)
> [jsk_fetch_startup] add speak_and_wait_recovery

- jsk_fetch_robot/jsk_fetch_startup/package.xml
- add run dependencies to jsk_fetch_startup's package.xml
+ `move_slow_and_clear`
+ `global_planner`
> [jsk_fetch_startup] fix dependencies

- jsk_fetch_robot/jsk_fetch.rosinstall.indigo
- jsk_fetch_robot/jsk_fetch.rosinstall.melodic
Fix remote uris in rosinstall from knorth55
> [jsk_fetch_startup] fix remote uris in rosinstall from knorth55

- jsk_fetch_robot/jsk_fetch_startup/launch/devices/realsense_nodelet.launch.xml
- jsk_fetch_robot/jsk_fetch_startup/launch/fetch.launch
- jsk_fetch_robot/jsk_fetch_startup/launch/fetch_realsense_bringup.launch
- Add a jsk version of realsense nodelet xml
- Make realsense nodelets standalone nodes
- Make realsense nodes to be respawn
> [jsk_fetch_startup] Make realsense nodes respawn

- jsk_fetch_robot/jsk_fetch_startup/launch/navigation/fetch_move_base_common_params.yaml
Update teb local planner's parameters to decrease backward motions
> [jsk_fetch_startup] update teb local planner's parameters

- jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app
- jsk_fetch_robot/jsk_fetch_startup/apps/time_signal/time_signal.app
I add tweet notifier in go_to_kitchen and time_signal app.
https://github.com/knorth55/app_manager_utils/commit/8dcb723f835523eec7b2879a3a0597cb42a91d01
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/235
> add tweet notifier in go_to_kitchen and time_signal

- jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l
> fix typo in navigation-utils.l

- jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l
check battery charing state at the end of kitchen demo.
I will test it later.
> check battery charging state at the end of kitchen demo

- jsk_fetch_robot/jsk_fetch_startup/launch/navigation/fetch_move_base_common_params.yaml
https://kaiyuzheng.me/documents/navguide.pdf
according to tunning guide, `cost_factor` should be around `0.8` with default `lethal_cost` and `neutral_cost`.
> set proper global_costmap cost_factor

- jsk_fetch_robot/jsk_fetch.rosinstall.melodic
I am sorry for my typo in my previous PR #124
> Fix local name typo
